### ISSUE TITLE
Main Site  To Do: Header Component

### ISSUE THREAD

**Issue by KashCodes** [Portfolio-Generator/Portfolio-Generator#12]
# Main Site  To Do: Header Component 
- [x] Header Component - Logged In/Off - Nav Bar w/ Log in/Out and Sign up options.
- [x] Site Name - Upper Righthand Side 
- [ ] Potential Logo - Upper Righthand Side 
- [x] Nav Bar 
> - [x] Demo 
> - [x] How to Setup 
> - [x] Contact Us 
> > #### If Logged In 
> > - [x] Portfolio Generator 
> > - [ ] *********Profile Settings ********* 
> > > - [ ]  *********Username {Change Username} ********* 
> > > - [ ]  *********Email {Change Email}  *********
> > > - [ ]  *********Password Edit *********
> > > - [ ] *********Email Edit *********
> > > - [ ]  *********Username Edit *********
> > > - [ ]  *********Payment/Donation *********
> > > - [ ]  *********User Demo Display *********
> > - [x] Log Out 
> > #### If Logged Out 
> > - [x] Log In Link 
> > > - [x]  Log In Modal {Username and Password}
> > - [x] Sign Up Link 
> > > - [x] Sign Up Modal {Username, Password, Email}

**Comment by Govepitr** [comment]
Site name is now in upper left hand side.

::Items ice boxed::
Potential Logo - Upper Righthand Side

*********Profile Settings *********
 *********Username {Change Username} *********
 *********Email {Change Email} *********
 *********Password Edit *********
 *********Email Edit *********
 *********Username Edit *********
 *********Payment/Donation *********
 *********User Demo Display *********
